{% set name = "fastds" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastds-{{ version }}.tar.gz
  sha256: 92c746c9195dd1951e20b8325bec187eb0ba7cb4b6820850628bcc9046ae26ba

build:
  number: 0
  noarch: python
  entry_points:
    - fds=fds.cli:main
    - sdf=fds.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - colorama ==0.4.4
    - dataclasses
    - humanize ==3.11.0
    - progress ==1.6
    - pyinquirer ==1.0.3
    - python >=3.6
    - requests ==2.26.0
    - validators ==0.18.2

test:
  imports:
    - fds
    - fds.domain
  commands:
    - pip check
    - fds --help
    - sdf --help
  requires:
    - pip

about:
  home: https://github.com/DAGsHub/fds
  summary: Command line wrapper for git and dvc
  license: MIT
  license_file: LICENSE
  description: |
    fds is a tool for Data Scientists made by DAGsHub to version control data
     and code at once. At a high level, fds is a command line wrapper around
     Git and DVC, meant to minimize the chances of human error, automate
     repetitive tasks, and provide a smoother landing for new users.

extra:
  recipe-maintainers:
    - thewchan
